### PR TITLE
(Small) Design Updates + Misc.

### PR DESCRIPTION
**Pull request by kidSoba**
This pull request adds following features / changes:

- password visibility toggles for all password fields
- remove deprecated code-references (to non-existent files, or the "ace-solarized-light" theme)
- neemgit links from the neem-cards open in new tabs (instead of in the same tab)
- adjusted side-card from the QA-page to show neem-name, -author, and description
- add navigation-arrows to related projects-carousel in QA-page

### CODE REVIEW

**Review by sasjonge — CHANGES_REQUESTED** [review]
Tested in in my local openEASE. We found some problems:
- If the description of a neem is too big it overflows on the neem discovery page.
- If the height of the browser window is too small on the QA page, then the sidebar isn't completly visible anymore (it vanishs under the footer).
- Could you change the author and date in the sidebar to a line of the form: "Mona Abdel-Keream, 12/18/20 13:38" ?

**Comment by kidSoba** [comment]
I'll have a look into all. Third point should be straight forward.

**Comment by kidSoba** [comment]
The points should all have been addressed with my changes, please check on your versions as well. A quick rundown:
- author/date format for side card on QA page adjusted to the desired format
- description texts in the neem-discovery don't overflow anymore; also set a fixed image height as it looks better on several screen sizes in my opinion
- sidebar in QA page is now scrollable and won't just vanish behind the footer; **but** it is a separate scroll from the page, because it has a fixed position for the responsive behavior implemented for mobile view -> this is just a workaround solution, so if desired I will try to find a better solution

**Comment by sasjonge** [comment]
Checked the code and everything looks fine. If @daniel86 is ok with it, we can merge this PR.

**Review by daniel86 — APPROVED** [review]

**Pull request merged**
