### PR TITLE
Footer and Legal pages

### PR DESCRIPTION
**Pull request by kidSoba**
Changes the footer and adds legal pages which are linked by the footer

### CODE REVIEW

**Comment by sasjonge** [comment]
Could we only show the new bigger footer on the homepage? When scrolling on QA Page the sidebar overlapt the footer. Therefore we had the small footer there. 

Also the grey lines under "Project Management" and "Contact Info" could be removed. Maybe a different font could be enough to highlight this headings?

**Comment by sasjonge** [comment]
Also could the social network icons not be moved to the bottom line? Then the rest could be stretched to be more centered.

**Comment by kidSoba** [comment]
Most issues stemmed from the branch not being rebased onto upstream/master. I did that and also slightly adjusted the side-bar. The view, at least for now, is optimized for phones and screens wider than 1600px. Other screen-sizes in-between are not optimal, but acceptable. This can be changed later though, maybe with a good concept for those screen-sizes.

I also kept the line under "Project Management" etc., as it helps separate content, especially in mobile views. Yet, if you still don't like it, let me know and I'll change it asap.

**Comment by kidSoba** [comment]
Page links and social media buttons should be vertically aligned now. Also, the QA-page should display the blue line only when scrolling down.

**Comment by sasjonge** [comment]
> Page links and social media buttons should be vertically aligned now.

The social media buttons are still right of the Page links, is that correct? I still think this way it looks a bit asymmetric. Maybe move the social media buttons above the Copyright notice but under the Project Management and Contact Info?

**Comment by kidSoba** [comment]
Done, please check if it's according to description :)

**Pull request merged**
