### PR TITLE
Refactor major code parts, make docker build deterministic, add first tests, add gitignore & travis.yml

### PR DESCRIPTION
**Pull request by kidSoba**
Refactored most of the modules for readability. Some tests were added already, but currently we don't know if this breaks anything, because we lack the test coverage.

The docker build was made deterministic, by building a base image and hosting it on docker-hub. Previously the most-current updates would be pulled on each build, which might cause changes to the configuration of the system, and since currently we are missing major testing coverage, we cannot risk that.

Also added a gitignore and travis.yml. If Travis-Ci is activated in the base repository, then it will run with the current configuration, which will run the current tests. Test coverage should be enhanced with future updates.

We have a problem, where upon login, a weird message containing html code and so on is displayed as an pop-up. Also there is an connection error, when checking the javascript console in the browser. The knowrob editor won't load.

Also O-Auth-Login was removed for now, as it was causing problems upon start-up etc.

### CODE REVIEW

**Comment by kidSoba** [comment]
So apparently the admin thing wouldn't crash the application, redirects would just take substantially longer. Still, connection errors persist and we get those weird pop-ups. The following three issues reference those bugs:

- navidJadid#7
- navidJadid#8
- navidJadid#9  

Please have a look and give feedback. We see those as important parts of the software and experience

**Comment by kidSoba** [comment]
We also have this issue with the screen overlay: navidJadid#10

**Comment by kidSoba** [comment]
Most importantly should be issue navidJadid#9. We assume when that is fixed, part of the other problems might get solved as well. Therefore, please have a look into that first.

**Comment by kidSoba** [comment]
Because I forgot to mention it elsewhere: I just remember, we also removed OAuth-Login for, because during setup it caused problems for start-up and we couldn't get it to run otherwise. I documented it in issue navidJadid#11. If things work properly again, consider adding it back in.

**Review by daniel86 — APPROVED** [review]
that's a big one.

**Pull request merged**
